# Generated by Django 4.2.23 on 2025-10-21 02:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoporteTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_soporte', to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='soporte_respuestas/', verbose_name='Imagen Adjunta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='paneladm.soporteticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200, verbose_name='Título o Detalle')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reuniones/', verbose_name='Imagen (Opcional)')),
                ('imprimir_etiqueta_al_asistir', models.BooleanField(default=True, help_text='Si se marca, se abrirá la ventana para imprimir la etiqueta del asistente al escanear su QR.', verbose_name='¿Imprimir etiqueta al escanear QR?')),
                ('asistentes', models.ManyToManyField(blank=True, related_name='reuniones_asistidas', to='usuario.usuario')),
                ('interesados', models.ManyToManyField(blank=True, related_name='reuniones_interesado', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Encuesta de Satisfacción', max_length=200)),
                ('activa', models.BooleanField(default=True, help_text='Los usuarios solo pueden ver y responder encuestas activas.')),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='paneladm.reunion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1 - Muy Malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(default=django.utils.timezone.now)),
                ('destacado', models.BooleanField(default=False, help_text='Marcar para mostrar como testimonio en la página de inicio.')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='paneladm.encuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuesta', to='usuario.usuario')),
            ],
            options={
                'unique_together': {('encuesta', 'usuario')},
            },
        ),
    ]
