# Generated by Django 4.2.23 on 2025-11-19 02:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_institucion_empresa_alter_usuario_rubro'),
        ('paneladm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanadorSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_participantes', models.CharField(help_text="Describe el grupo del que se seleccionó el ganador (Ej: 'Todos los Usuarios', 'Asistentes a Evento X')", max_length=255)),
                ('fecha_sorteo', models.DateTimeField(default=django.utils.timezone.now)),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteos_ganados', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Ganador de Sorteo',
                'verbose_name_plural': 'Ganadores de Sorteos',
                'ordering': ['-fecha_sorteo'],
            },
        ),
    ]
