# Generated by Django 4.2.23 on 2025-10-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('rubro', models.CharField(blank=True, choices=[('Tecnología y Desarrollo', (('desarrollo_software', 'Desarrollo de Software'), ('desarrollo_web', 'Desarrollo Web'), ('desarrollo_movil', 'Desarrollo Móvil'), ('ia_machine_learning', 'Inteligencia Artificial / Machine Learning'), ('ciberseguridad', 'Ciberseguridad'), ('analisis_datos', 'Análisis de Datos / Big Data'), ('devops', 'DevOps'), ('infraestructura_cloud', 'Infraestructura y Cloud'), ('ecommerce', 'E-commerce'))), ('Diseño y Creatividad', (('diseno_grafico', 'Diseño Gráfico'), ('diseno_ux_ui', 'Diseño UX/UI'), ('produccion_audiovisual', 'Producción Audiovisual'), ('fotografia', 'Fotografía'), ('marketing_digital', 'Marketing Digital'), ('redes_sociales', 'Gestión de Redes Sociales'), ('publicidad', 'Publicidad'))), ('Negocios y Consultoría', (('consultoria_negocios', 'Consultoría de Negocios'), ('finanzas_contabilidad', 'Finanzas y Contabilidad'), ('recursos_humanos', 'Recursos Humanos'), ('ventas_desarrollo_negocios', 'Ventas y Desarrollo de Negocios'), ('legal_asesoria', 'Legal y Asesoría'), ('gestion_proyectos', 'Gestión de Proyectos'))), ('Salud y Bienestar', (('salud_medicina', 'Salud y Medicina'), ('psicologia_coaching', 'Psicología y Coaching'), ('nutricion', 'Nutrición'), ('deporte_fitness', 'Deporte y Fitness'))), ('Otros Sectores', (('educacion', 'Educación y Formación'), ('inmobiliario', 'Sector Inmobiliario'), ('turismo_hoteleria', 'Turismo y Hotelería'), ('gastronomia', 'Gastronomía'), ('construccion_arquitectura', 'Construcción y Arquitectura'), ('agroindustria', 'Agroindustria'), ('otro', 'Otro')))], help_text='Tu profesión o área de expertise.', max_length=100, null=True, verbose_name='Rubro')),
                ('rubro_otro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar otro rubro')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('etiqueta_emojis', models.CharField(blank=True, max_length=10)),
                ('nombre_empresa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Empresa/Pyme')),
                ('rubro_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro de la Empresa')),
                ('descripcion_empresa', models.TextField(blank=True, null=True, verbose_name='Descripción de la Empresa')),
                ('web_empresa', models.URLField(blank=True, null=True, verbose_name='Sitio Web de la Empresa')),
                ('buscando', models.CharField(blank=True, help_text='Ej: Inversionistas, socios, clientes, etc.', max_length=255, null=True, verbose_name='¿Qué buscas en la comunidad?')),
                ('es_admin', models.BooleanField(default=False)),
                ('es_ayudante', models.BooleanField(default=False)),
                ('es_totem', models.BooleanField(default=False, help_text='Designa a este usuario como una cuenta para un quiosco/tótem de check-in.')),
                ('cantidad_asistencias', models.IntegerField(default=0, verbose_name='Cantidad de Asistencias')),
                ('perfil_publico', models.BooleanField(default=True, help_text='Permite que otros miembros vean tu perfil en el directorio.')),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
    ]
