# Generated by Django 4.2.23 on 2025-10-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='buscando',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rubro_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rubro_otro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='web_empresa',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rubro',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor / Docente'), ('director', 'Director de Carrera / Administrativo'), ('externo', 'Entidad Externa / Colaborador')], help_text='Tu rol dentro de la comunidad.', max_length=100, null=True, verbose_name='Rol en la comunidad'),
        ),
    ]
