# Generated by Django 4.2.23 on 2025-10-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_buscando_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rubro_otro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar otro rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rubro',
            field=models.CharField(blank=True, choices=[('Comunidad INACAP', (('estudiante', 'Estudiante'), ('egresado', 'Egresado / Titulado'), ('docente', 'Docente'), ('directivo', 'Directivo / Administrativo'), ('investigador', 'Investigador'))), ('Colaboradores Externos', (('empresa', 'Empresa / Empleador'), ('expositor', 'Expositor / Experto'), ('postulante', 'Postulante / Futuro Alumno'))), ('otro', 'Otro Rol')], help_text='Tu rol dentro de la comunidad.', max_length=100, null=True, verbose_name='Rol en la comunidad'),
        ),
    ]
