# Generated by Django 4.2.23 on 2025-10-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_rubro_otro_alter_usuario_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Carrera o Especialidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede'),
        ),
    ]
