# Generated by Django 4.2.23 on 2025-10-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_carrera_usuario_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carrera_otro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Especificar otra carrera'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sede_otro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar otra sede'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sede',
            field=models.CharField(blank=True, choices=[('Antofagasta', 'Antofagasta'), ('Apoquindo', 'Apoquindo'), ('Chillán', 'Chillán'), ('Concepción', 'Concepción'), ('Curicó', 'Curicó'), ('La Florida', 'La Florida'), ('La Serena', 'La Serena'), ('Maipú', 'Maipú'), ('Osorno', 'Osorno'), ('Pérez Rosales', 'Pérez Rosales'), ('Puerto Montt', 'Puerto Montt'), ('Punta Arenas', 'Punta Arenas'), ('Rancagua', 'Rancagua'), ('Santiago Centro', 'Santiago Centro'), ('Santiago Sur', 'Santiago Sur'), ('Talca', 'Talca'), ('Temuco', 'Temuco'), ('Valparaíso', 'Valparaíso'), ('otro', 'Otra Sede')], max_length=100, null=True, verbose_name='Sede'),
        ),
    ]
