# Generated by Django 4.2.23 on 2025-10-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_carrera_otro_usuario_sede_otro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Área Tecnología', (('ing_informatica', 'Ingeniería en Informática'), ('analista_programador', 'Analista Programador'), ('ing_ciberseguridad', 'Ingeniería en Ciberseguridad'))), ('Área Administración', (('ing_adm_empresas', 'Ingeniería en Administración de Empresas'), ('cont_auditor', 'Contador Auditor'))), ('otro', 'Otra Carrera / Especialidad')], max_length=150, null=True, verbose_name='Carrera o Especialidad'),
        ),
    ]
