# Generated by Django 4.2.23 on 2025-10-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Tecnologías de la Información y Ciberseguridad', (('ing_informatica', 'Ingeniería en Informática'), ('analista_programador', 'Analista Programador'), ('ciberseguridad', 'Ingeniería en Ciberseguridad'))), ('Administración y Negocios', (('ing_adm_empresas', 'Ingeniería en Administración de Empresas'), ('contador_auditor', 'Contador Auditor'), ('comercio_exterior', 'Comercio Exterior'))), ('Mecánica y Mantenimiento', (('ing_mecanica_electromovilidad', 'Ingeniería en Mecánica y Electromovilidad Automotriz'), ('tec_mantenimiento_industrial', 'Técnico en Mantenimiento Industrial'), ('ing_maquinaria_pesada', 'Ingeniería en Maquinaria Pesada'))), ('Electricidad y Electrónica', (('ing_electronica_sistemas', 'Ingeniería en Electrónica y Sistemas Inteligentes'), ('tec_electricidad_industrial', 'Técnico en Electricidad Industrial'), ('ing_telecomunicaciones', 'Ingeniería en Telecomunicaciones, Conectividad y Redes'))), ('Diseño y Comunicación', (('diseno_digital', 'Diseño Digital Profesional'), ('diseno_moda', 'Diseño y Producción de Moda'))), ('Salud', (('tec_enfermeria', 'Técnico en Enfermería'), ('laboratorista_clinico', 'Laboratorista Clínico y Banco de Sangre'))), ('Otras Áreas', (('gastronomia', 'Gastronomía'), ('construccion_civil', 'Construcción Civil'), ('ing_agricola', 'Ingeniería Agrícola'))), ('otro', 'Otra Carrera / Especialidad')], max_length=150, null=True, verbose_name='Carrera o Especialidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sede',
            field=models.CharField(blank=True, choices=[('Zona Norte', (('Arica', 'Arica'), ('Iquique', 'Iquique'), ('Calama', 'Calama'), ('Antofagasta', 'Antofagasta'), ('Copiapó', 'Copiapó'), ('La Serena', 'La Serena'), ('Valparaíso', 'Valparaíso'))), ('Región Metropolitana', (('Apoquindo', 'Apoquindo'), ('Maipú', 'Maipú'), ('Renca', 'Renca'), ('Ñuñoa', 'Ñuñoa'), ('Santiago Centro', 'Santiago Centro'), ('Santiago Sur', 'Santiago Sur'), ('La Granja', 'La Granja'), ('Puente Alto', 'Puente Alto'))), ('Zona Sur', (('Rancagua', 'Rancagua'), ('Curicó', 'Curicó'), ('Talca', 'Talca'), ('Chillán', 'Chillán'), ('Concepción-Talcahuano', 'Concepción-Talcahuano'), ('San Pedro de la Paz', 'San Pedro de la Paz'), ('Los Ángeles', 'Los Ángeles'), ('Temuco', 'Temuco'), ('Valdivia', 'Valdivia'), ('Osorno', 'Osorno'), ('Puerto Montt', 'Puerto Montt'), ('Coyhaique', 'Coyhaique'), ('Punta Arenas', 'Punta Arenas'))), ('otro', 'Otra Sede')], max_length=100, null=True, verbose_name='Sede'),
        ),
    ]
