# Generated by Django 4.2.23 on 2025-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_carrera_alter_usuario_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='institucion_empresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Institución o Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rubro',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo'), ('externo', 'Externo')], help_text='Tu rol dentro de la comunidad.', max_length=100, null=True, verbose_name='Rol'),
        ),
    ]
